import Groq from 'groq-sdk';
import dotenv from 'dotenv';

dotenv.config();

const apiKey = process.env.GROQ_API_KEY;
const isRealApiKey = apiKey && apiKey !== 'gsk_your_groq_api_key_here' && apiKey.trim().length > 10;

let groq = null;
if (isRealApiKey) {
  try {
    groq = new Groq({ apiKey });
    console.log('[GroqService] Groq SDK initialized successfully with API Key.');
  } catch (err) {
    console.warn('[GroqService] Failed to initialize Groq SDK:', err.message);
  }
} else {
  console.log('[GroqService] No valid GROQ_API_KEY detected. Using agent heuristic fallback system.');
}

/**
 * Clean LLM response string to extract pure JSON
 */
export const cleanJsonString = (str) => {
  if (!str) return '';
  let cleaned = str.trim();
  if (cleaned.startsWith('```')) {
    cleaned = cleaned.replace(/^```(?:json)?\n?/, '').replace(/\n?```$/, '').trim();
  }
  return cleaned;
};

// Currently supported active Groq models
const SUPPORTED_GROQ_MODELS = [
  process.env.GROQ_MODEL || 'openai/gpt-oss-120b',
  'openai/gpt-oss-120b',
  'openai/gpt-oss-20b',
  'qwen/qwen3.6-27b',
  'groq/compound'
];

/**
 * Call Groq API to generate chat completion with model fallback loop
 */
export const callGroqLLM = async (systemPrompt, userPrompt, options = {}) => {
  if (!groq) {
    throw new Error('NO_GROQ_KEY');
  }

  const temperature = options.temperature ?? 0.3;
  const messages = [
    { role: 'system', content: systemPrompt },
    { role: 'user', content: userPrompt }
  ];

  let lastError = null;

  // Try supported active Groq models in sequence
  for (const model of SUPPORTED_GROQ_MODELS) {
    try {
      const completion = await groq.chat.completions.create({
        model,
        messages,
        temperature,
        max_tokens: options.max_tokens || 4000
      });

      let responseText = completion.choices[0]?.message?.content;
      if (responseText) {
        // Strip out internal thinking blocks if generated by reasoning models
        responseText = responseText.replace(/<think>[\s\S]*?<\/think>/gi, '').trim();
        if (responseText) {
          return responseText;
        }
      }
    } catch (err) {
      lastError = err;
      console.warn(`[GroqService] Model '${model}' failed: ${err.message}. Trying next model...`);
    }
  }

  console.error('[GroqService] All Groq models failed. Falling back to heuristic generator.');
  const apiErr = new Error(lastError?.message || 'GROQ_API_ERROR');
  apiErr.isApiError = true;
  throw apiErr;
};

/**
 * Call Groq API and strictly parse JSON output with retry logic
 */
export const callGroqStructuredJSON = async (systemPrompt, userPrompt, retryCount = 1) => {
  try {
    const rawResponse = await callGroqLLM(
      `${systemPrompt}\nIMPORTANT: You MUST respond ONLY with valid JSON. Do not include introductory or concluding text.`,
      userPrompt
    );

    const cleaned = cleanJsonString(rawResponse);
    return JSON.parse(cleaned);
  } catch (err) {
    if (err.message === 'NO_GROQ_KEY' || err.isApiError) {
      throw err;
    }

    if (retryCount > 0) {
      try {
        console.warn('[GroqService] JSON parse failed. Retrying with strict JSON prompt...');
        const strictUserPrompt = `${userPrompt}\n\nCRITICAL FIX: Your previous response was not valid JSON. Output strictly JSON matching the required schema. No markdown formatting.`;
        const retryResponse = await callGroqLLM(systemPrompt, strictUserPrompt);
        const cleaned = cleanJsonString(retryResponse);
        return JSON.parse(cleaned);
      } catch (retryErr) {
        throw retryErr;
      }
    }
    
    throw err;
  }
};
