import React, { useEffect } from 'react';
import { useRoadmap } from '../context/RoadmapContext';
import { Sparkles, Clock, CheckCircle, X, HelpCircle, Flame } from 'lucide-react';

export const TodayTaskModal = ({ isOpen, onClose }) => {
  const { todayPlan, fetchTodayPlan, loadingToday } = useRoadmap();

  useEffect(() => {
    if (isOpen && !todayPlan) {
      fetchTodayPlan();
    }
  }, [isOpen]);

  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/75 backdrop-blur-md animate-fade-in">
      <div className="glass-panel w-full max-w-2xl rounded-3xl border border-brand-500/30 p-6 md:p-8 space-y-6 shadow-glow-indigo max-h-[90vh] overflow-y-auto">
        <div className="flex items-center justify-between border-b border-gray-800 pb-4">
          <div className="flex items-center space-x-3">
            <div className="p-2 rounded-2xl bg-gradient-to-r from-brand-600 to-indigo-600 shadow-glow-indigo">
              <Sparkles className="w-6 h-6 text-cyan-300 animate-pulse" />
            </div>
            <div>
              <h2 className="text-xl font-bold text-white flex items-center gap-2">
                Today's Customized Study Plan
              </h2>
              <p className="text-xs text-gray-400">
                Generated by Manager Agent based on current roadmap & weak areas
              </p>
            </div>
          </div>
          <button
            onClick={onClose}
            className="p-2 text-gray-400 hover:text-white rounded-xl hover:bg-gray-800 transition-colors"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {loadingToday ? (
          <div className="py-12 text-center space-y-3">
            <div className="w-10 h-10 border-4 border-brand-500 border-t-transparent rounded-full animate-spin mx-auto" />
            <p className="text-sm font-semibold text-gray-300">
              Manager Agent is synthesizing today's optimal study session...
            </p>
          </div>
        ) : todayPlan ? (
          <div className="space-y-6">
            {/* Header info card */}
            <div className="p-4 rounded-2xl bg-gradient-to-r from-brand-900/40 via-indigo-900/30 to-dark-card border border-brand-500/30 flex flex-col sm:flex-row sm:items-center justify-between gap-3">
              <div>
                <span className="text-xs text-brand-accent font-bold uppercase tracking-wider">
                  {todayPlan.phaseTitle}
                </span>
                <h3 className="text-lg font-bold text-white flex items-center gap-2 mt-0.5">
                  <Flame className="w-5 h-5 text-amber-400" />
                  Focus: {todayPlan.focusTopic}
                </h3>
              </div>
              <div className="flex items-center space-x-2 px-3 py-1.5 rounded-xl bg-dark-bg border border-brand-500/30 text-white font-bold text-sm shrink-0">
                <Clock className="w-4 h-4 text-cyan-400" />
                <span>{todayPlan.totalDurationMinutes || 120} Mins Total</span>
              </div>
            </div>

            {/* Rationale explanation box */}
            {todayPlan.rationale && (
              <div className="p-4 rounded-2xl bg-dark-bg/60 border border-gray-800 space-y-1 text-xs">
                <div className="flex items-center space-x-2 font-bold text-gray-300">
                  <HelpCircle className="w-4 h-4 text-indigo-400" />
                  <span>Why these tasks were selected for you today:</span>
                </div>
                <p className="text-gray-400 leading-relaxed pl-6">{todayPlan.rationale}</p>
              </div>
            )}

            {/* Time-Bucket Tasks */}
            <div className="space-y-3">
              <h4 className="text-xs font-semibold text-gray-400 uppercase tracking-wider">
                Actionable Tasks Breakdown
              </h4>
              <div className="space-y-3">
                {todayPlan.tasks?.map((task, idx) => (
                  <div
                    key={idx}
                    className="p-4 rounded-2xl bg-dark-card border border-gray-800 hover:border-brand-500/40 transition-all flex flex-col sm:flex-row sm:items-center justify-between gap-3"
                  >
                    <div className="space-y-1">
                      <div className="flex items-center space-x-2">
                        <span className="w-6 h-6 rounded-full bg-brand-500/20 text-brand-accent text-xs font-bold flex items-center justify-center">
                          {idx + 1}
                        </span>
                        <span className="text-sm font-bold text-white">{task.title}</span>
                        <span className="text-[10px] uppercase font-semibold px-2 py-0.5 rounded bg-gray-800 text-gray-400">
                          {task.type || 'Study'}
                        </span>
                      </div>
                      <p className="text-xs text-gray-400 pl-8">{task.action}</p>
                    </div>
                    <div className="flex items-center space-x-2 shrink-0 self-end sm:self-center">
                      <span className="text-xs font-bold text-cyan-300 px-3 py-1 rounded-xl bg-dark-bg border border-cyan-500/20">
                        {task.durationMinutes} mins
                      </span>
                    </div>
                  </div>
                ))}
              </div>
            </div>

            {/* Regenerate Today Plan */}
            <div className="flex justify-end space-x-3 pt-2 border-t border-gray-800">
              <button
                onClick={fetchTodayPlan}
                className="px-4 py-2 rounded-xl bg-dark-hover hover:bg-gray-800 text-gray-300 font-semibold text-xs transition-all flex items-center gap-2"
              >
                <Sparkles className="w-4 h-4 text-cyan-400" />
                Refresh Today Plan
              </button>
              <button
                onClick={onClose}
                className="px-5 py-2 rounded-xl bg-gradient-to-r from-brand-600 to-indigo-600 text-white font-semibold text-xs shadow-glow-indigo hover:opacity-90 transition-all"
              >
                Got It! Start Learning
              </button>
            </div>
          </div>
        ) : (
          <div className="py-8 text-center text-gray-400 text-sm">
            Could not load today plan. Make sure your profile and roadmap are generated first.
          </div>
        )}
      </div>
    </div>
  );
};
